from mathapp.domain.errors.mathapp_error import MathAppError

class NotFoundError(MathAppError):
	pass
